---
# tasks file for enqack.crowd

- name: Add daemon
  template:
    src: "{{ role_path }}/templates/crowd.service.j2"
    dest: "/etc/systemd/system/crowd.service"
    owner: "{{ crowd_run_user }}"
    group: "{{ crowd_run_group }}"
    mode: 0664

- name: Force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Enable and start daemon
  systemd:
    name: crowd.service
    enabled: true
    state: restarted
